services:
  db:
    image: postgres:16
    container_name: generic-crud-db
    environment:
      POSTGRES_DB: genericdb
      POSTGRES_USER: generic
      POSTGRES_PASSWORD: changemegeneric
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U generic -d genericdb"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    build: .
    container_name: generic-crud-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/genericdb
      SPRING_DATASOURCE_USERNAME: generic
      SPRING_DATASOURCE_PASSWORD: changemegeneric
    ports:
      - "8080:8080"
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: generic-crud-pgadmin
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8082:80"
    restart: unless-stopped

volumes:
  pgdata: